// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathAdvertisementGetAdsSwiper = "/advertisement/homeSwiper"

// AdvertisementBMServer is the server API for Advertisement service.
type AdvertisementBMServer interface {
	// 获取首页广告轮播图
	GetAdsSwiper(ctx context.Context, req *google_protobuf1.Empty) (resp *AdsSwiper, err error)
}

var AdvertisementSvc AdvertisementBMServer

func advertisementGetAdsSwiper(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := AdvertisementSvc.GetAdsSwiper(c, p)
	c.JSON(resp, err)
}

// RegisterAdvertisementBMServer Register the blademaster route
func RegisterAdvertisementBMServer(e *bm.Engine, server AdvertisementBMServer) {
	AdvertisementSvc = server
	e.GET("/advertisement/homeSwiper", advertisementGetAdsSwiper)
}
