// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	api "easymarket-go-server/common/goods/api"
	api1 "easymarket-go-server/common/topic/api"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xb7, 0xac, 0xc4, 0x9f, 0xb0, 0x6c, 0xc5, 0x08, 0x84, 0x08, 0x10, 0xd8, 0xdc, 0x9b,
	0x08, 0x78, 0x02, 0x76, 0x91, 0x72, 0xe1, 0x54, 0x21, 0x0e, 0xdc, 0x9c, 0xc4, 0xb8, 0x86, 0x24,
	0x63, 0x62, 0xef, 0x4a, 0xbd, 0xf2, 0x0a, 0x5c, 0x78, 0x0d, 0xde, 0xa2, 0x47, 0x24, 0x5e, 0x00,
	0x0a, 0x0f, 0x82, 0x3c, 0x71, 0x68, 0xda, 0xe0, 0xb2, 0xb7, 0x58, 0xdf, 0xcc, 0xf7, 0x9b, 0xf9,
	0xec, 0x04, 0x37, 0x98, 0x92, 0x89, 0x6a, 0xd1, 0x20, 0x1c, 0x33, 0xa5, 0x12, 0xcd, 0xdb, 0x0b,
	0x59, 0xf0, 0xe4, 0xe2, 0x69, 0x38, 0x13, 0xd2, 0x2c, 0xce, 0xf3, 0xa4, 0xc0, 0x3a, 0x15, 0x28,
	0x30, 0xa5, 0xb2, 0xfc, 0xfc, 0x1d, 0x9d, 0xe8, 0x40, 0x5f, 0x5d, 0x7b, 0xf8, 0x40, 0x20, 0x8a,
	0x8a, 0x6f, 0xaa, 0x78, 0xad, 0xcc, 0xd2, 0x89, 0x0f, 0x9d, 0xc8, 0x94, 0x4c, 0x59, 0xd3, 0xa0,
	0x61, 0x46, 0x62, 0xa3, 0x9d, 0x9a, 0x72, 0xa6, 0x97, 0x35, 0x6b, 0x3f, 0x70, 0x33, 0x13, 0x38,
	0xb3, 0x33, 0xf0, 0x36, 0x2d, 0xb0, 0xae, 0xb1, 0x49, 0x05, 0x62, 0xa9, 0xbb, 0xc6, 0x7e, 0xd4,
	0xfd, 0x0d, 0x06, 0x95, 0x2c, 0xb6, 0x1b, 0x9e, 0x7d, 0xbd, 0x16, 0x1c, 0xbe, 0x50, 0x0a, 0x8a,
	0xe0, 0x28, 0xe3, 0x26, 0xb3, 0x96, 0xaf, 0xa4, 0x36, 0x10, 0x26, 0x64, 0x3f, 0x58, 0x3b, 0x21,
	0x71, 0xce, 0x3f, 0x86, 0x91, 0x47, 0xb3, 0x8d, 0x73, 0xae, 0xe3, 0x7b, 0x9f, 0xbe, 0xff, 0xfe,
	0x7c, 0xe5, 0x36, 0x4c, 0x53, 0xa6, 0x94, 0x1b, 0xb3, 0xb2, 0xa6, 0x79, 0x70, 0xdc, 0x43, 0x5e,
	0x72, 0xc3, 0x64, 0x05, 0x4f, 0x3c, 0x56, 0x9d, 0x6c, 0x61, 0xfe, 0x41, 0x74, 0x0c, 0x04, 0x3a,
	0x82, 0x60, 0x03, 0x82, 0xf7, 0xc4, 0x38, 0x6d, 0x59, 0x53, 0x3a, 0xc6, 0xc9, 0xd8, 0x81, 0xe4,
	0x01, 0xe4, 0xbf, 0x25, 0xbb, 0xac, 0xdc, 0xaa, 0xb0, 0xa0, 0xd0, 0xa8, 0x92, 0x42, 0x7b, 0xec,
	0xb3, 0xe9, 0x92, 0xf9, 0x67, 0x72, 0x7f, 0xbb, 0xc7, 0xc9, 0x11, 0xa4, 0x4b, 0xee, 0x4d, 0x70,
	0x3d, 0xe3, 0xe6, 0xb5, 0xbd, 0x40, 0x08, 0x13, 0xba, 0xc8, 0xa1, 0x09, 0x09, 0x5d, 0x5a, 0x3e,
	0x6d, 0x77, 0x03, 0xaa, 0x03, 0x41, 0x1b, 0x50, 0x09, 0x6d, 0x10, 0x79, 0xfa, 0x37, 0x0b, 0xec,
	0xd3, 0x77, 0x17, 0xe8, 0x1e, 0x1c, 0x2d, 0xa0, 0x82, 0x69, 0x0f, 0x9a, 0xf3, 0x8a, 0x19, 0x5e,
	0xc2, 0x89, 0x77, 0x56, 0xd2, 0x2f, 0x83, 0x0b, 0x09, 0x77, 0x07, 0x60, 0x80, 0x6b, 0x9d, 0xbd,
	0x21, 0xe2, 0x19, 0x33, 0x5c, 0x60, 0xbb, 0xa4, 0xed, 0xe2, 0x71, 0xfc, 0xbd, 0x7e, 0xb6, 0x90,
	0x55, 0xe9, 0x79, 0x0a, 0xb6, 0x26, 0x73, 0x1e, 0x63, 0x6a, 0xe1, 0x1c, 0xfa, 0x27, 0x7e, 0x73,
	0x40, 0x85, 0x47, 0x7e, 0xa2, 0x85, 0xed, 0x95, 0x75, 0x7c, 0x97, 0x40, 0x53, 0xb8, 0xb5, 0x05,
	0x3a, 0xbd, 0xbf, 0xfa, 0x19, 0x1d, 0xac, 0xd6, 0xd1, 0xe4, 0xdb, 0x3a, 0x9a, 0xfc, 0x58, 0x47,
	0x93, 0x2f, 0xbf, 0xa2, 0x83, 0xb7, 0x87, 0x4c, 0xc9, 0xfc, 0x2a, 0xfd, 0xd5, 0xcf, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x4e, 0x78, 0x29, 0xbe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppClient interface {
	// 获取商品列表
	GetGoodsList(ctx context.Context, in *api.GoodsReq, opts ...grpc.CallOption) (*api.GoodsListRes, error)
	// 获取商品详情
	GetGoodsDetail(ctx context.Context, in *api.GoodsDetailReq, opts ...grpc.CallOption) (*api.GoodsRes, error)
	// 获取制造商详情
	GetBrandDetail(ctx context.Context, in *api.BrandsDetailReq, opts ...grpc.CallOption) (*api.BrandsDetailRes, error)
	// 获取制造商列表
	GetBrandList(ctx context.Context, in *api.BrandsListReq, opts ...grpc.CallOption) (*api.BrandListRes, error)
	// 获取专题详情
	GetTopic(ctx context.Context, in *api1.TopicReq, opts ...grpc.CallOption) (*api1.TopicRes, error)
	// 获取专题列表
	GetTopicList(ctx context.Context, in *api1.TopicListReq, opts ...grpc.CallOption) (*api1.TopicListRes, error)
	// 获取相似专题列表
	GetTopicRelated(ctx context.Context, in *api1.TopicRelatedReq, opts ...grpc.CallOption) (*api1.TopicListRes, error)
	// 获取子商品分类列表
	GetCategoryList(ctx context.Context, in *api.CategoryChildReq, opts ...grpc.CallOption) (*api.CateGoryListRes, error)
	// 获取商品分类详情
	GetCategory(ctx context.Context, in *api.CategoryReq, opts ...grpc.CallOption) (*api.CategoryRes, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) GetGoodsList(ctx context.Context, in *api.GoodsReq, opts ...grpc.CallOption) (*api.GoodsListRes, error) {
	out := new(api.GoodsListRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetGoodsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetGoodsDetail(ctx context.Context, in *api.GoodsDetailReq, opts ...grpc.CallOption) (*api.GoodsRes, error) {
	out := new(api.GoodsRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetGoodsDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetBrandDetail(ctx context.Context, in *api.BrandsDetailReq, opts ...grpc.CallOption) (*api.BrandsDetailRes, error) {
	out := new(api.BrandsDetailRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetBrandDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetBrandList(ctx context.Context, in *api.BrandsListReq, opts ...grpc.CallOption) (*api.BrandListRes, error) {
	out := new(api.BrandListRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetBrandList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetTopic(ctx context.Context, in *api1.TopicReq, opts ...grpc.CallOption) (*api1.TopicRes, error) {
	out := new(api1.TopicRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetTopicList(ctx context.Context, in *api1.TopicListReq, opts ...grpc.CallOption) (*api1.TopicListRes, error) {
	out := new(api1.TopicListRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetTopicList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetTopicRelated(ctx context.Context, in *api1.TopicRelatedReq, opts ...grpc.CallOption) (*api1.TopicListRes, error) {
	out := new(api1.TopicListRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetTopicRelated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetCategoryList(ctx context.Context, in *api.CategoryChildReq, opts ...grpc.CallOption) (*api.CateGoryListRes, error) {
	out := new(api.CateGoryListRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetCategoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetCategory(ctx context.Context, in *api.CategoryReq, opts ...grpc.CallOption) (*api.CategoryRes, error) {
	out := new(api.CategoryRes)
	err := c.cc.Invoke(ctx, "/app.service.v1.App/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
type AppServer interface {
	// 获取商品列表
	GetGoodsList(context.Context, *api.GoodsReq) (*api.GoodsListRes, error)
	// 获取商品详情
	GetGoodsDetail(context.Context, *api.GoodsDetailReq) (*api.GoodsRes, error)
	// 获取制造商详情
	GetBrandDetail(context.Context, *api.BrandsDetailReq) (*api.BrandsDetailRes, error)
	// 获取制造商列表
	GetBrandList(context.Context, *api.BrandsListReq) (*api.BrandListRes, error)
	// 获取专题详情
	GetTopic(context.Context, *api1.TopicReq) (*api1.TopicRes, error)
	// 获取专题列表
	GetTopicList(context.Context, *api1.TopicListReq) (*api1.TopicListRes, error)
	// 获取相似专题列表
	GetTopicRelated(context.Context, *api1.TopicRelatedReq) (*api1.TopicListRes, error)
	// 获取子商品分类列表
	GetCategoryList(context.Context, *api.CategoryChildReq) (*api.CateGoryListRes, error)
	// 获取商品分类详情
	GetCategory(context.Context, *api.CategoryReq) (*api.CategoryRes, error)
}

// UnimplementedAppServer can be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (*UnimplementedAppServer) GetGoodsList(ctx context.Context, req *api.GoodsReq) (*api.GoodsListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsList not implemented")
}
func (*UnimplementedAppServer) GetGoodsDetail(ctx context.Context, req *api.GoodsDetailReq) (*api.GoodsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsDetail not implemented")
}
func (*UnimplementedAppServer) GetBrandDetail(ctx context.Context, req *api.BrandsDetailReq) (*api.BrandsDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandDetail not implemented")
}
func (*UnimplementedAppServer) GetBrandList(ctx context.Context, req *api.BrandsListReq) (*api.BrandListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandList not implemented")
}
func (*UnimplementedAppServer) GetTopic(ctx context.Context, req *api1.TopicReq) (*api1.TopicRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopic not implemented")
}
func (*UnimplementedAppServer) GetTopicList(ctx context.Context, req *api1.TopicListReq) (*api1.TopicListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicList not implemented")
}
func (*UnimplementedAppServer) GetTopicRelated(ctx context.Context, req *api1.TopicRelatedReq) (*api1.TopicListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicRelated not implemented")
}
func (*UnimplementedAppServer) GetCategoryList(ctx context.Context, req *api.CategoryChildReq) (*api.CateGoryListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryList not implemented")
}
func (*UnimplementedAppServer) GetCategory(ctx context.Context, req *api.CategoryReq) (*api.CategoryRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_GetGoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetGoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetGoodsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetGoodsList(ctx, req.(*api.GoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetGoodsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GoodsDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetGoodsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetGoodsDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetGoodsDetail(ctx, req.(*api.GoodsDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetBrandDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.BrandsDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetBrandDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetBrandDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetBrandDetail(ctx, req.(*api.BrandsDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetBrandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.BrandsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetBrandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetBrandList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetBrandList(ctx, req.(*api.BrandsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api1.TopicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetTopic(ctx, req.(*api1.TopicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetTopicList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api1.TopicListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetTopicList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetTopicList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetTopicList(ctx, req.(*api1.TopicListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetTopicRelated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api1.TopicRelatedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetTopicRelated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetTopicRelated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetTopicRelated(ctx, req.(*api1.TopicRelatedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CategoryChildReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetCategoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetCategoryList(ctx, req.(*api.CategoryChildReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.service.v1.App/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetCategory(ctx, req.(*api.CategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.service.v1.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsList",
			Handler:    _App_GetGoodsList_Handler,
		},
		{
			MethodName: "GetGoodsDetail",
			Handler:    _App_GetGoodsDetail_Handler,
		},
		{
			MethodName: "GetBrandDetail",
			Handler:    _App_GetBrandDetail_Handler,
		},
		{
			MethodName: "GetBrandList",
			Handler:    _App_GetBrandList_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _App_GetTopic_Handler,
		},
		{
			MethodName: "GetTopicList",
			Handler:    _App_GetTopicList_Handler,
		},
		{
			MethodName: "GetTopicRelated",
			Handler:    _App_GetTopicRelated_Handler,
		},
		{
			MethodName: "GetCategoryList",
			Handler:    _App_GetCategoryList_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _App_GetCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
