// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/go-kratos/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// ActivityServiceErrCode ecode
var (
	TokenTimeOut = ecode.New(1001)
	TokenIsError = ecode.New(1002)
	TokenIsNew   = ecode.New(1003)
)
