// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathGoodsGetGoods = "/goods/getList"

// GoodsBMServer is the server API for Goods service.
type GoodsBMServer interface {
	GetGoods(ctx context.Context, req *GoodsReq) (resp *GoodsRes, err error)
}

var GoodsSvc GoodsBMServer

func goodsGetGoods(c *bm.Context) {
	p := new(GoodsReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := GoodsSvc.GetGoods(c, p)
	c.JSON(resp, err)
}

// RegisterGoodsBMServer Register the blademaster route
func RegisterGoodsBMServer(e *bm.Engine, server GoodsBMServer) {
	GoodsSvc = server
	e.GET("/goods/getList", goodsGetGoods)
}
