// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"easymarket-go-server/common/advertisement/internal/dao"
	"easymarket-go-server/common/advertisement/internal/server/grpc"
	"easymarket-go-server/common/advertisement/internal/server/http"
	"easymarket-go-server/common/advertisement/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	daoDao, err := dao.New()
	if err != nil {
		return nil, nil, err
	}
	serviceService, cleanup, err := service.New(daoDao)
	if err != nil {
		return nil, nil, err
	}
	engine, err := http.New(serviceService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server, err := grpc.New(serviceService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, cleanup2, err := NewApp(serviceService, engine, server)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
